### ISSUE TITLE
I do not have a numpad yet you assume your users have numpads

### ISSUE THREAD

**Issue by hughbord** [mikedesu/textrpg#3]
darkmage i was just trying out textrpg and i do not have a numpad (as i am a bird irl) so diagonal working and stuff is much harder, u gotta remap the keys or allow the user to remap the keys somehow bro.

**Comment by rj1** [comment]
+1

**Comment by mikedesu** [comment]
Remapping keys to personal taste is a project goal. I greatly want to provide this functionality to users in the near future, so I will elevate that as a priority. I apologize for forced numpad use. Do you have any desired keys you'd like for movement besides the numpad? Nethack's default is very awkward for me, which is where the initial motivation for this came from.

**Comment by dingopride** [comment]
I am raising this to P0 as it breaks ADA compliance.  Do we need to take this repo offline until this is addressed?

**Comment by mikedesu** [comment]
Negative. If n0m4d can play CoD with his face, you can use the numbers at the top of the keyboard until I add additional input keys. Closing for now.

**Comment by funkpower** [comment]
We need to re-open this issue
